config/routes.rb
Rails.application.routes.draw do
  resources :users, 	only: [:index, :show, :new, :create, :destroy]
  resources :sessions, 	only: [:new, :create, :destroy]
  resources :events, 	only: [:index, :new, :create, :show]

  match "/signup",  to: "users#new", 		via: :get
  match "/signin",  to: "sessions#new", 	via: :get
  match "/signout",	to: "sessions#destroy", via: :delete

  root "users#index"
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, :class_name => "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save 	{ self.email = email.downcase }
  before_create :create_remember_token

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  has_many :created_events, :foreign_key => "creator_id", :class_name => "Event"

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  	@events = Event.all
  end

  def new
  	@event = Event.new
  end

  def create
  	@event = current_user.created_events.build(events_params)
  	if @event.save
  	  flash[:success] = "Event saved!"
  	  redirect_to root_url
  	else
  	  render 'new'
  	end
  end

  def show
  	@event = Event.find(params[:id])
  end


  private
    def events_params
      params.require(:event).permit(:location, :date, :description)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
  	  render 'new'
  	end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
      flash[:error] = "Welcome to the events app"
  	  redirect_to @user
  	else
  	  render 'new'
  	end
  end

  def destroy
  end	

  private 
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = User
  end

  def signed_in?
  	!current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/index.html.erb
<div class="container">

  <h1> Here are all events </h1>
  <% @events.each do |e| %>
    <p> <%= e.location %> | <%= e.date %> | <%= e.description %> </p>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="container">
  <%= form_for(@event) do |f| %>

    <%= f.label :location %><br>
    <%= f.text_field :location %> <br>

    <%= f.label :date %><br>
    <%= f.date_field :date %><br>
    
    <%= f.label :description %><br>
    <%= f.text_area :description %><br>

    <br>

    <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="container">
  <h1>Creator</h1>
  <ul>
    <li><%= @event.creator.name %></li>
    <li><%= @event.creator.email %></li>
  </ul>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <%= link_to "evENTE", root_path, id: "logo" %>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if signed_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-error">
    The form contains <%= pluralize(@user.errors.count, "error") %>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
<h1>All users</h1>

<% if @users.any? %>
  <ul>
    <% @users.each do |user| %>
    <li><%= user.name %>, <%= user.email %></li>
    <% end %>
  </ul>
<% else %>
  <p> No users yet </p>
<% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <%= form_for (@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>

    <%= f.label :email %><br>
    <%= f.text_field :email %><br>

    <%= f.label :password %><br>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>

    <br> 
    
    <%= f.submit "Sign up" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
   
  <h1><%= @user.name %> <%= @user.email %></h1>
  
  <h2>Created events</h2>
  <ul>
    <% @user.created_events.each do |f| %>
      <li><%= f.location %> | <%= f.date %> | <%= f.description %></li>
    <% end %>
  </ul>
</div>